spring:
  application:
    name: cs-mail-service
  aop:
    auto: true
    proxy-target-class: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
    production_mail:
      username: ${PRODUCTION_MAIL_USERNAME}
      password: ${PRODUCTION_MAIL_PASSWORD}
    debug: ${MAIL_DEBUG}
  kafka:
    bootstrap-servers: ${KAFKA1_BOOTSTRAP_SERVICE_URL},${KAFKA2_BOOTSTRAP_SERVICE_URL},${KAFKA3_BOOTSTRAP_SERVICE_URL}
    consumer:
      properties:
        session:
          timeout:
            ms: 60000
        reconnect:
          backoff:
            ms: 1000
            max:
              ms: 20000

server:
  port: ${SERVER_INTERNAL_PORT}

database:
  url: ${MS_DB_URL}
  username: ${MS_DB_USER}
  password: ${MS_DB_PASSWORD}
  schema: ${MS_DB_SCHEMA}

config:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    org.careerseekers.csmailservice.config.FlywayConfig: ${FLYWAY_LOGGING}

grpc:
  client:
    users-service:
      address: ${USERS_SERVICE_URL}
      negotiation-type: plaintext